import { useEffect, useMemo, useState } from "react";
import { ShieldCheck, UserPlus, Users } from "lucide-react";
import toast from "react-hot-toast";
import api, { getErrorMessage } from "../api/client";
import { useAuth } from "../context/AuthContext";

export default function AdminUsers(){
  const { user: currentUser } = useAuth();
  const [users,setUsers]=useState([]); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [busyId,setBusyId]=useState(null);
  const [form,setForm]=useState({name:"",email:"",password:"",role:"employee"});
  const load=async()=>{setLoading(true);try{const {data}=await api.get("/users");setUsers(data.users)}catch(error){toast.error(getErrorMessage(error,"Could not load team"))}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const summary=useMemo(()=>({active:users.filter(u=>u.status==="active").length,admins:users.filter(u=>u.role==="admin").length}),[users]);
  const add=async(e)=>{e.preventDefault();setSubmitting(true);try{const {data}=await api.post("/users",form);setUsers(current=>[data.user,...current]);setForm({name:"",email:"",password:"",role:"employee"});toast.success("Team member added")}catch(error){toast.error(getErrorMessage(error,"Could not add member"))}finally{setSubmitting(false)}};
  const toggle=async(member)=>{const status=member.status==="active"?"disabled":"active";if(status==="disabled"&&!window.confirm(`Disable ${member.name}? They will be signed out on their next request.`))return;setBusyId(member.id);try{const {data}=await api.patch(`/users/${member.id}/status`,{status});setUsers(current=>current.map(item=>item.id===member.id?data.user:item));toast.success(`Member ${status}`)}catch(error){toast.error(getErrorMessage(error,"Could not update member"))}finally{setBusyId(null)}};
  return <div className="relative mx-auto max-w-[1600px] p-4 sm:p-6 lg:p-10"><div><p className="text-sm font-semibold text-indigo-600">Workspace administration</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-white md:text-slate-900">Team members</h1><p className="mt-2 text-sm text-slate-400 md:text-slate-500">Create accounts and control who can access the workspace.</p></div>
  <div className="mt-6 grid gap-4 sm:grid-cols-3"><Stat label="Total members" value={users.length} icon={Users}/><Stat label="Active accounts" value={summary.active} icon={ShieldCheck}/><Stat label="Administrators" value={summary.admins} icon={ShieldCheck}/></div>
  <form onSubmit={add} className="card-premium mt-6 p-5 lg:p-6"><div className="mb-4 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><UserPlus size={19}/></div><div><h2 className="font-bold text-slate-800">Add a team member</h2><p className="text-xs text-slate-400">Create credentials for an employee or another admin.</p></div></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><Input placeholder="Full name" value={form.name} set={v=>setForm({...form,name:v})}/><Input type="email" placeholder="Work email" value={form.email} set={v=>setForm({...form,email:v})}/><Input type="password" placeholder="Temporary password" value={form.password} set={v=>setForm({...form,password:v})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="input-premium"><option value="employee">Employee</option><option value="admin">Admin</option></select><button disabled={submitting} className="btn-primary">{submitting?"Adding…":"Add member"}</button></div><p className="mt-3 text-xs text-slate-400">Password must be at least 8 characters and include a letter and number.</p></form>
  <section className="card-premium mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-800">Workspace directory</h2></div>{loading?<div className="animate-pulse space-y-4 p-6">{[1,2,3].map(i=><div key={i} className="h-14 rounded-xl bg-slate-100"/>)}</div>:<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3.5">Member</th><th className="px-5 py-3.5">Role</th><th className="px-5 py-3.5">Status</th><th className="px-5 py-3.5 text-right">Action</th></tr></thead><tbody>{users.map(member=><tr key={member.id} className="border-t border-slate-100 hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-indigo-100 to-violet-100 font-bold text-indigo-700">{member.name.charAt(0).toUpperCase()}</div><div><p className="font-semibold text-slate-800">{member.name}{member.id===currentUser?.id&&<span className="ml-2 text-xs font-medium text-indigo-500">You</span>}</p><p className="text-xs text-slate-400">{member.email}</p></div></div></td><td className="px-5 py-4"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold capitalize text-indigo-700">{member.role}</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${member.status==="active"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{member.status}</span></td><td className="px-5 py-4 text-right"><button disabled={busyId===member.id||member.id===currentUser?.id} onClick={()=>toggle(member)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40">{busyId===member.id?"Updating…":member.status==="active"?"Disable":"Enable"}</button></td></tr>)}</tbody></table></div>}</section></div>
}
function Stat({label,value,icon:Icon}){return <div className="card-premium p-5"><div className="flex items-center justify-between"><div><p className="text-2xl font-bold text-slate-800">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div><div className="grid h-11 w-11 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><Icon size={20}/></div></div></div>}
function Input({type="text",placeholder,value,set}){return <input required minLength={type==="password"?8:2} type={type} placeholder={placeholder} value={value} onChange={e=>set(e.target.value)} className="input-premium"/>}
