import { BookOpen, CheckCircle2, LockKeyhole, Sparkles } from "lucide-react";
import { useState } from "react";
import toast from "react-hot-toast";
import { Link, useNavigate } from "react-router-dom";
import { getErrorMessage } from "../api/client";
import { useAuth } from "../context/AuthContext";

export default function Login() {
  const [form, setForm] = useState({ email: "", password: "" }); const [submitting, setSubmitting] = useState(false); const { login } = useAuth(); const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); try { await login(form); toast.success("Welcome back"); navigate("/dashboard"); } catch (error) { toast.error(getErrorMessage(error, "Unable to log in")); } finally { setSubmitting(false); } };
  return <AuthLayout><div className="mb-8"><div className="mb-5 inline-flex rounded-2xl bg-indigo-50 p-3 text-indigo-600"><LockKeyhole/></div><h1 className="text-3xl font-bold tracking-tight text-slate-900">Welcome back</h1><p className="mt-2 text-sm leading-6 text-slate-500">Sign in to continue to your secure enterprise knowledge workspace.</p></div><form onSubmit={submit} className="space-y-4"><Field label="Work email" type="email" value={form.email} onChange={(v) => setForm({...form, email:v})}/><Field label="Password" type="password" value={form.password} onChange={(v) => setForm({...form, password:v})}/><button disabled={submitting} className="btn-primary w-full py-3">{submitting ? "Signing in…" : "Sign in"}</button></form><p className="mt-6 text-center text-sm text-slate-500">New organization? <Link className="font-semibold text-indigo-600 hover:text-indigo-700" to="/register">Create workspace</Link></p></AuthLayout>;
}
export function AuthLayout({children}){return <div className="grid min-h-screen bg-slate-950 lg:grid-cols-[1.1fr_.9fr]"><section className="relative hidden overflow-hidden p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,_rgba(99,102,241,.4),_transparent_30%),radial-gradient(circle_at_bottom_right,_rgba(139,92,246,.25),_transparent_35%)]"/><div className="relative flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10 backdrop-blur"><BookOpen size={22}/></div><div><p className="font-bold">KnowledgeBase AI</p><p className="text-xs text-slate-400">Enterprise intelligence</p></div></div><div className="relative max-w-xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-semibold text-indigo-200"><Sparkles size={14}/> Built for secure knowledge teams</span><h2 className="mt-6 text-5xl font-bold leading-tight tracking-tight">Turn scattered documents into trusted organizational knowledge.</h2><div className="mt-8 space-y-3 text-slate-300">{["Private organization workspaces","Role-based access controls","Cloud-ready document intelligence"].map(item=><p key={item} className="flex items-center gap-3"><CheckCircle2 size={18} className="text-emerald-400"/>{item}</p>)}</div></div><p className="relative text-xs text-slate-500">Secure by design · Ready for RAG and cloud deployment</p></section><section className="grid place-items-center px-4 py-10 sm:px-8"><div className="w-full max-w-md rounded-[2rem] bg-white p-7 shadow-2xl shadow-black/20 sm:p-9">{children}</div></section></div>}
function Field({ label, type="text", value, onChange }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input required type={type} value={value} onChange={(e)=>onChange(e.target.value)} className="input-premium" autoComplete={type==="password"?"current-password":"email"}/></label> }
